version: "3.8"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.20
    depends_on:
      gitea-cache:
        condition: service_healthy
    environment:
      - APP_NAME="Gitea"
      - USER_UID=1000
      - USER_GID=1000
      - USER=git
      - RUN_MODE=prod
      - DOMAIN=$GITEA_URL
      - SSH_DOMAIN=$GITEA_URL
      - HTTP_PORT=3000
      - ROOT_URL=https://$GITEA_URL
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=sqlite3
      - GITEA__cache__ENABLED=true
      - GITEA__cache__ADAPTER=redis
      - GITEA__cache__HOST=redis://gitea-cache:6379/0?pool_size=100&idle_timeout=180s
      - GITEA__cache__ITEM_TTL=24h

    restart: always
    volumes:
      - ${GITEA_STORAGE_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    networks:
      - proxy
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    labels:
      traefik.enable: true
      traefik.docker.network: proxy # Specify which network to use for traefik, since there are multiple network defined
      traefik.http.routers.gitea.entrypoints: https
      traefik.http.routers.gitea.rule: "Host(`$GITEA_URL`)"
      traefik.http.routers.gitea.service: gitea-service
      traefik.http.services.gitea-service.loadbalancer.server.port: 3000

  gitea-cache:
    container_name: gitea-cache
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 30
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  proxy:
    external: true

volumes:
  db_data:
  git_data: