version: "3"

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:2.10.4
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    # I prefer to command config for traefik eventhough it is less readable than traefik.yml since `traefik.yml` is a static configuration and doesn't accept environment variables
    command:
      - --global.checkNewVersion=true # check for updates
      - --global.sendAnonymousUsage=false # do not send anonymous statistics
      - --providers.docker.network=proxy # define default network to monitor for docker provider
      - --providers.docker.exposedbydefault=false # do not expose docker hosts per default
      # - --providers.docker.swarmModeRefreshSeconds=15s # defeine swarm mode fresh seconds
      - --providers.providersThrottleDuration=2s # define throttle duration
      - --providers.file.watch=true # monitor file provider for changes
      - --providers.file.filename=/etc/traefik/fileConfig.yml # location of the dynamic configuration
      - --entrypoints.http.address=:80 # entrypoint for unencrypted http
      - --entrypoints.http.forwardedHeaders.trustedIPs=103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/13,104.24.0.0/14,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32 # define cloudflare ip ranges as trusted
      - --entrypoints.http.http.redirections.entryPoint.to=https # automatic redirect from http to https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https # automatic redirect from http to https
      - --entrypoints.https.address=:443 # entrypoint for encrypted https
      - --entrypoints.https.forwardedHeaders.trustedIPs=103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/13,104.24.0.0/14,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32 # define cloudflare ip ranges as trusted
      - --entrypoints.https.http.middlewares=security-headers@file,rate-limit@file # define default middlewares for all proxy entries
      - --api.dashboard=true # enable traefik api dashboard
      - --api.insecure=true # expose traefik api dashboard on TCP/8080 without need for router
      - --entrypoints.ssh.address=:2222 # entrypoint for service-ssh, use for services like Gitea, Onedev. Use 23 to avoid conflict with ssh port 22
      # ####################################################
      # # !!! ADJUST TO YOUR INFRASTRUCTURE SETUP BELOW !!!!
      - --entrypoints.https.http.tls.certresolver=cloudflare # define default cert resolver
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN_NAME} # define main domain, change to your domain
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN_NAME} # define sans domain, change to your domain
      # - --certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL} # define your cloudflare email address
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true # enable dns challenge to obtain wildcard certificates
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare # define provider for certificates
      - --certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json # define acme path for certificate information
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53 # define cloudflare dns servers as the resolver

      # ####################################################
      - --log.level=INFO # enable log level
      - --accesslog=true # enable access logs
      - --accesslog.filepath=/logs/traefik.log # define access log path
      - --accesslog.format=json # set access log format to json instead clm
      - --accesslog.bufferingsize=0 # set access log buffer size to 0
      - --accesslog.filters.statuscodes=400-599 # only log http errors in logs; alternatively set 200-599 to include successful http requests
      - --accesslog.fields.headers.defaultmode=drop # drop all headers
      - --serversTransport.insecureSkipVerify=true # set insecureSkipVerify to true to allow self-signed certificates
    ports:
      - 443:443
      - 80:80
      - 2222:2222

    environment:
      - TZ=Europe/Copenhagen
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - AUTHELIA_URL=${AUTHELIA_URL}
      - TRAEFIK_BASIC_AUTH_USER=${TRAEFIK_BASIC_AUTH_USER}
      - TRAEFIK_BASIC_AUTH_PASSWORD=${TRAEFIK_BASIC_AUTH_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # pass docker socket as read-only
      - ./volumes/logs:/logs # bind mount volume for persistent traefik logs
      - ./volumes:/etc/traefik/ # bind mount volume for persistent traefik data
      - ./fileConfig.yml:/etc/traefik/fileConfig.yml # override fileConfig

    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entryPoints=https
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_URL}`) # Define the subdomain for the traefik dashboard.
      - traefik.http.routers.api.service=api@internal # Enable Traefik API.
      - traefik.http.routers.api.middlewares=basic-auth@file
      # - traefik.http.routers.api.middlewares=local-ipwhitelist@file,basic-auth@file # protect dashboard with basic auth and restrict access to private class subnets only
