version: "3"

networks:
  proxy:
    external: true
  nextcloud:

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - nextcloud-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    networks:
      - default

  nextcloud-redis:
    image: redis:6.2.3
    container_name: nextcloud-redis
    # hostname: nextcloud-redis
    networks:
      - default
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - nextcloud-redis:/var/lib/redis

  nextcloud-app:
    image: nextcloud:27.0.1
    # ports:
    #   - 8080:80
    container_name: nextcloud-app
    restart: always
    networks:
      - proxy
      - default
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      OVERWRITEHOST: ${NEXTCLOUD_URL}
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      MYSQL_HOST: nextcloud-db:3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ${NEXTCLOUD_WEBROOT}:/var/www/html
      - ${NEXTCLOUD_DATA_PATH}:/var/www/html/data
    labels:
      # Reverse proxy configuration
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html
      traefik.enable: true
      traefik.docker.network: proxy # Specify which network to use for traefik, since there are multiple network defined
      traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_URL}`)
      traefik.http.routers.nextcloud.entrypoints: https
      traefik.http.routers.nextcloud.middlewares: nextcloud_secure_headers,nextcloud_redirectregex

      # nextcloud_redirectregex middleware
      traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent: true
      traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex: "https://(.*)/.well-known/(?:card|cal)dav"
      traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement: "https://$${1}/remote.php/dav"

      # nextcloud_secure_headers middleware
      traefik.http.middlewares.nextcloud_secure_headers.headers.customFrameOptionsValue: ALLOW-FROM https://$NEXTCLOUD_URL
      traefik.http.middlewares.nextcloud_secure_headers.headers.contentSecurityPolicy: frame-ancestors 'self' $NEXTCLOUD_URL *.$NEXTCLOUD_URL
      traefik.http.middlewares.nextcloud_secure_headers.headers.stsSeconds: 155520011
      traefik.http.middlewares.nextcloud_secure_headers.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.nextcloud_secure_headers.headers.stsPreload: true
      traefik.http.middlewares.nextcloud_secure_headers.headers.customresponseheaders.X-Frame-Options: SAMEORIGIN

volumes:
  nextcloud-db:
  nextcloud-redis:
