version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '40080:80'
      - '40081:81'
      - '40443:443'
    volumes:
      - ${NGINX_VOLUME_PATH}/data:/data
      - ${NGINX_VOLUME_PATH}/letsencrypt:/etc/letsencrypt
    networks:
      - npm

networks:
  npm:

