version: "3"

networks:
  proxy:
    external: true

services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      traefik.enable: true
      traefik.docker.network: proxy # Specify which network to use for traefik, since there are multiple network defined
      traefik.http.routers.whoami.rule: Host(`${WHOAMI_URL}`)
      traefik.http.routers.whoami.entrypoints: https
    networks:
      - proxy

volumes:
  certs:
